### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by brodavi** [zcanter/aframe-gradient-sky#2]
`npm install --save aframe-gradient-sky`

then

`require('aframe-gradient-sky')`

doesn't appear to work as expected. I get the error:

`Error: Cannot find module 'aframe-gradient-sky' from '/src/aframeproject'`

at run-time. I am using browserify.

**Comment by zcanter** [comment]
I will look into it right now. I have to be honest I'm quite inexperienced when it comes to NPM. I would suggest use the browser setup method for now.

**Comment by zcanter** [comment]
Okay it appears I just had the wrong source path in the package.json. Try it again and let me know if it works (still working on the animation issue).

**Comment by brodavi** [comment]
hey there! thanks for the amazing response times :)

I think, however, that you want to do "./dist/gradientsky.min.js" for the path in package.json?

**Comment by zcanter** [comment]
Oh man you are right! Apologies still new to this! New version (1.0.4) should work! Thank you for letting me know.

**Comment by brodavi** [comment]
Happy to help! You're awesome for contributing :)
