### ISSUE TITLE
transparency in setting colors

### ISSUE THREAD

**Issue by rmrbytes** [zcanter/aframe-gradient-sky#5]
Is there a way to set transparency to either the bottom or top color?

My use case is to use a cone and set colors from the bottom being dark and shaded to the top being transparent. Thanks

**Comment by zcanter** [comment]
Hi @rrrepos - honestly it's been ages since I last looked at this code. I'll see what I can do!

But I'm curious if it is transparent, what will be in the sky?

**Comment by rmrbytes** [comment]
Thanks @zcanter . I am not using it in the sky but as a shader on a cone. I thought it would work in this manner. Appreciate your taking time

**Comment by zcanter** [comment]
Very interesting. I can't guarantee anything too quickly as I am currently quite busy, but I will try.
Either way, I am planning on overhauling this project during the Winter break.

**Comment by rmrbytes** [comment]
Sure. Will stay clued in. Thanks.

**Comment by zcanter** [comment]
Hey @rrrepos unfortunately I can't easily find a way to do the transparency update. I'm sure there is a way but I don't have the time to do a deep dive. Perhaps in the future sometime. Best of luck to you in the mean time.

**Comment by rmrbytes** [comment]
Thanks @zcanter . Enjoy the winter break.
